name: pytest

on:
  push:
    branches:
      - main
    paths:
      - "script/**"
  pull_request:
    branches:
      - main
    paths:
      - "script/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/script
        run: uv run pytest tests
